DROP TABLE IF EXISTS forecast;
DROP TABLE IF EXISTS history;


CREATE TABLE forecast (
    time DATETIME PRIMARY KEY,
    temp DECIMAL(3,1) NOT NULL
);

CREATE TABLE history (
    time DATETIME PRIMARY KEY,
    temp DECIMAL(3,1)
);