DROP TABLE IF EXISTS forecast;
DROP TABLE IF EXISTS history;


CREATE TABLE forecast (
    time DATETIME PRIMARY KEY,
    temp DECIMAL(3,1) NOT NULL
);

CREATE TABLE history (
    time DATETIME PRIMARY KEY,
    temp DECIMAL(3,1)
)
-- CREATE TABLE user (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   username TEXT UNIQUE NOT NULL,
--   password TEXT NOT NULL
-- );

-- CREATE TABLE post (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   author_id INTEGER NOT NULL,
--   created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   title TEXT NOT NULL,
--   body TEXT NOT NULL,
--   FOREIGN KEY (author_id) REFERENCES user (id)
-- );